name = "kv"
compatibility_date = "2026-02-21"
compatibility_flags = ["nodejs_compat"]
main = ".vercel/output/static/_worker.js"

[assets]
directory = ".vercel/output/static"
binding = "ASSETS"

# Secrets (set via `wrangler secret put`)
# AUTH_SECRET
# DB_HOST
# DB_PORT
# DB_USER
# DB_PASSWORD
# DB_DATABASE
# NEXT_PUBLIC_SITE_URL
