name = "kv-website"
compatibility_date = "2025-02-01"
main = ".vercel/output/static/_worker.js"

[assets]
directory = ".vercel/output/static"

# Secrets (set via `wrangler secret put`)
# AUTH_SECRET
# DATABASE_URL
