export const facilities = [
  {
    slug: "restaurant",
    title: "Restaurant",
    badge: "Popular",
    description: "All-day dining with seasonal menus and local favorites.",
    longDescription:
      "Our restaurant serves curated breakfast, lunch, and dinner with regional specialties and chef-crafted seasonal menus.",
    images: ["/hero-hotel.jpg", "/hero-hotel.jpg", "/hero-hotel.jpg"],
    timing: "7:00 am - 11:00 pm",
    bestFor: "Dining and family meals",
    capacity: "Indoor + private seating",
    access: "Guests and events",
    highlights: ["All-day dining", "Seasonal menu", "Family-friendly seating", "Private dining on request"],
    amenities: ["Chef specials", "Private dining", "Kids options", "Table service"],
  },
  {
    slug: "lawn",
    title: "Lawn",
    badge: "Event favorite",
    description: "Open green lawn for weddings, gatherings, and outdoor celebrations.",
    longDescription:
      "A spacious, beautifully maintained lawn ideal for weddings, receptions, and evening social events under open skies.",
    images: ["/hero-hotel.jpg", "/hero-hotel.jpg", "/hero-hotel.jpg"],
    timing: "Morning to late evening",
    bestFor: "Weddings and receptions",
    capacity: "Large outdoor events",
    access: "Pre-booked events",
    highlights: ["Wedding-ready setup", "Outdoor seating", "Event decor flexibility", "Photo-friendly venue"],
    amenities: ["Decor flexibility", "Lighting setup", "Open-air stage", "Event support"],
  },
  {
    slug: "swimming-pool",
    title: "Swimming Pool",
    badge: "Relaxation zone",
    description: "A calm pool deck for morning laps and evening rest.",
    longDescription:
      "Relax by the pool or enjoy a refreshing swim with comfortable deck seating and a peaceful resort ambience.",
    images: ["/hero-hotel.jpg", "/hero-hotel.jpg", "/hero-hotel.jpg"],
    timing: "7:00 am - 8:00 pm",
    bestFor: "Leisure and relaxation",
    capacity: "Family-friendly deck",
    access: "In-house guests",
    highlights: ["Poolside deck", "Lounger seating", "Evening ambience", "Family relaxation zone"],
    amenities: ["Deck loungers", "Towel support", "Poolside seating", "Shower area"],
  },
  {
    slug: "banquet",
    title: "Banquet",
    badge: "Premium venue",
    description: "One elegant banquet space for weddings and celebrations.",
    longDescription:
      "Our banquet hall is designed for premium events with customizable layouts for ceremonies, receptions, and corporate gatherings.",
    images: ["/hero-hotel.jpg", "/hero-hotel.jpg", "/hero-hotel.jpg"],
    timing: "As per event schedule",
    bestFor: "Weddings and conferences",
    capacity: "Medium to large gatherings",
    access: "Pre-booked events",
    highlights: ["Elegant interiors", "Flexible seating layout", "Event coordination support", "AV setup possible"],
    amenities: ["Stage setup", "AV support", "Event planning", "Catering linkage"],
  },
  {
    slug: "small-hall",
    title: "Small Hall",
    badge: "Private events",
    description: "Ideal for meetings, private dinners, or intimate events.",
    longDescription:
      "A compact and versatile indoor space suitable for private gatherings, team meetings, and focused celebrations.",
    images: ["/hero-hotel.jpg", "/hero-hotel.jpg", "/hero-hotel.jpg"],
    timing: "As per booking",
    bestFor: "Meetings and private events",
    capacity: "Small group setup",
    access: "Pre-booked events",
    highlights: ["Intimate events", "Meeting-friendly", "Private dining setup", "Comfortable indoor space"],
    amenities: ["Flexible seating", "AC hall", "Private setup", "Service support"],
  },
];
